[project]
name = "timechimp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pandas-stubs==2.3.3.251219",
    "setuptools>=80.9.0",
    "undetected-chromedriver>=3.5.5",
]
